network <- list()
network <- insert_node(network,'Level',invalidate_CPT = FALSE)
network <- insert_node(network,'Employees',invalidate_CPT = FALSE)
network <- insert_node(network,'Contractors',invalidate_CPT = FALSE)
network <- insert_node(network,'Fraud')
network <- insert_node(network,'Income')
network <- insert_node(network,'Amount',invalidate_CPT = FALSE)
network <- insert_node(network,'Intensity',invalidate_CPT = FALSE)

network <- add_parent_child_rel(network, 'Level','Fraud')
network <- add_parent_child_rel(network, 'Level','Income')

network <- add_state_to_node(network,'Employees','1000')
network <- add_state_to_node(network,'Employees','1100')
network <- add_state_to_node(network,'Employees','1200')
network <- add_state_to_node(network,'Contractors','100')
network <- add_state_to_node(network,'Level','Clerk')
network <- add_state_to_node(network,'Level','Manager')
network <- add_state_to_node(network,'Level','Executive')
network <- add_state_to_node(network,'Amount','1000')
network <- add_state_to_node(network,'Intensity','0.5')
network <- add_state_to_node(network,'Intensity','2.5')
network <- add_state_to_node(network,'Intensity','7.5')
network <- add_state_to_node(network,'Fraud','FALSE')
network <- add_state_to_node(network,'Fraud','TRUE')
network <- add_state_to_node(network,'Income','1')
network <- add_state_to_node(network,'Income','1.5')
network <- add_state_to_node(network,'Income','2.0')

network <- add_CPT_to_node(network,'Employees',c(0.25,0.5,0.25))
network <- add_CPT_to_node(network,'Contractors',c(1))
network <- add_CPT_to_node(network,'Level',c(0.25,0.5,0.25))
network <- add_CPT_to_node(network,'Intensity',c(0.5,0.15,0.8))
network <- add_CPT_to_node(network,'Amount',c(1))
network <- add_CPT_to_node(network,'Fraud',c(0.0015,0.9985,0.0010,0.999,5e-4,0.9995))
network <- add_CPT_to_node(network,'Income',c(1,0,0,0,1,0,0,0,1))

save(network, file = 'Fraudmodel.RData')